---
sudo: required

language: python
python: "2.7"

services:
  - docker

branches:
  only:
    - master

before_script:
  - docker pull ubuntu:14.04
  - docker run -dt --name flask-uwsgi-nginx-ubuntu-14.04 --privileged -v $(pwd)/:/flask-uwsgi-nginx ubuntu:14.04
  - docker ps -a

script:
  - docker exec flask-uwsgi-nginx-ubuntu-14.04 /flask-uwsgi-nginx/ci_ubuntu_14.04.sh
  - docker exec -d flask-uwsgi-nginx-ubuntu-14.04 /opt/flask_github_jobs/flask_github_jobs.sh
  - docker exec flask-uwsgi-nginx-ubuntu-14.04 /flask-uwsgi-nginx/tests/test.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
