---
sudo: required

language: python
python: "2.7"

services:
  - docker

branches:
  only:
    - master

before_script:
  - docker pull ubuntu:14.04
  - docker run -d ubuntu:14.04 /bin/sh
  - docker ps -a

script:
  - docker run --rm -v /usr/bin:/usr/bin --privileged -v $(pwd)/:/flask-uwsgi-nginx ubuntu:14.04 /bin/sh -c " cd /flask-uwsgi-nginx; ./ci.sh"
