---
sudo: required

language: python
python: "2.7"

services:
  - docker

branches:
  only:
    - master

before_script:
  - docker pull ubuntu:14.04
  - docker run -d --name flask_uwsgi_nginx --privileged -v $(pwd)/:/flask-uwsgi-nginx ubuntu:14.04 bash
  - docker ps -a

script:
  - docker exec -it flask_uwsgi_nginx "cd /flask-uwsgi-nginx; ./ci.sh"
