---

- name: 'find systemctl'
  shell: 'find / -iname systemctl'
  become: yes

- import_tasks: 'system.yml'

- import_tasks: 'pyenv.yml'

- import_tasks: 'build.yml'

- import_tasks: 'service.yml'

- import_tasks: 'nginx.yml'

- import_tasks: 'tests.yml'
