---

####
# point nginx at the uwsgi socket
# serve static content with nginx instead of uwsgi
####
- name: get uwsgi static root
  shell: 'ls -d -1 {{ venv_dir }}/lib/python*/site-packages/{{ app_module }}/static'
  register: uwsgi_static_root
- name: get uwsgi static folders
  shell: 'ls -d -1 {{ venv_dir }}/lib/python*/site-packages/{{ app_module }}/static/**'
  register: uwsgi_static_folders
- name: nginx config
  template:
    src: templates/nginx.conf.j2
    dest: '/etc/nginx/sites-available/{{ app_name }}.conf'
    mode: 'u=rwx,g=rx,o=rx'
  notify:
     - 'restart nginx'
- file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent
- file:
    src: '/etc/nginx/sites-available/{{ app_name }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ app_name }}.conf'
    state: link
  notify:
     - 'restart nginx'
