---

####
# start flask app under uwsgi
####
#- name: app init script
#  template:
#    src: templates/systemd_service.j2
#    dest: '/etc/systemd/system/{{ app_name }}.service'
#    mode: 'u=rwx,g=rx,o=rx'
- name: app init script
  template:
    src: templates/upstart_service.j2
    dest: '/etc/init/{{ app_name }}.conf'
    mode: 'u=rwx,g=rx,o=rx'
- name: uwsgi configs
  template:
    src: templates/uwsgi.ini.j2
    dest: "{{ app_dir }}/{{ app_name }}.ini"
    owner: '{{ app_user }}'
    group: '{{ app_user }}'
    mode: 'u=rwx,g=rx,o=rx'
  notify:
    - 'stop {{ app_name }}'
    - 'start {{ app_name }}'
