---

####
# system group and user, + bash profile for pyenv
####
- group:
    name: '{{ app_user }}'
    state: present
- user:
    name: '{{ app_user }}'
    shell: /bin/bash
    groups: '{{ app_user }}'
- name: setup pyenv bash profile for {{ app_user }}
  template:
    src: templates/pyenv_profile.sh.j2
    dest: '/home/{{ app_user }}/.bash_profile'
    owner: '{{ app_user }}'
    group: '{{ app_user }}'
    mode: 'u=rwx,g=rx,o=rx'

####
# app directories
####
- name: make folders
  file:
    state: directory
    path: '{{ item }}'
    owner: '{{ app_user }}'
    group: '{{ app_user }}'
  with_items:
    - '{{ log_dir }}'
    - '{{ app_dir }}'
    - '{{ app_source_dir }}'
    - '{{ socket_dir }}'

####
# add nginx user to app group
###
- package:
    name: nginx
    state: present
- user:
    name: 'www-data'
    groups: '{{ app_user }}'
    append: true
