---

####
# check health endpoint
####

# make sure nginx has restarted before we try to test it
- meta: flush_handlers

# hit the health endpoint
- uri:
    url: 'http://localhost:{{ app_port }}{{ app_health_ep }}'
    return_content: yes
  register: healthy

- name: Fail if not healthy
  fail:
  when: healthy.status != 200
